### ISSUE TITLE
Allow limitation to groups

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/officeonline#48]
In order to control the necessary licenses of the Office back-end, I'd like to be able to limit the app usage to certain user groups, just as it is possible for a lot of other apps in Nextcloud:

![image](https://user-images.githubusercontent.com/1804221/99078472-bb38ae00-25be-11eb-855b-e4e102d83ca2.png)

**Comment by alx-tuilmenau** [comment]
The limitation to groups does not really work yet. I found following problems (If limit to a group is set):
- if someone accesses a file via a public link (no logged in user), office will be loaded always and it's possible to edit the file (there should be an option to turn it off for anonymous access)
- if a  user is logged in, but not member of the group, office is also loaded, but displays an error "content blocked", so maybe the WOPI request fails

To solve the first thing, I added "else return" to the "if ($currentUser !== null) {" in appinfo/app.php. But the more logical way is maybe to remove this if statement here complete and let the PermissionManager handle NULL user objets correctly, based on a config option.

The second thing is strange, because the viewer.js / Application class should not be loaded by app.php if the user is not a member of the group. But, I don't know why and where, it's loaded anyway. I duplicated the check from app.php to the begin of the Application.php constructor and created a "enabled" field in the class, set in the constructor (and exited the contructor after this if false). I used this field to exit "registerProvider" after calling immediatly, if false.

**Comment by Orchal** [comment]
> The limitation to groups does not really work yet. I found following problems (If limit to a group is set):
> 
> * if someone accesses a file via a public link (no logged in user), office will be loaded always and it's possible to edit the file (there should be an option to turn it off for anonymous access)
> * if a  user is logged in, but not member of the group, office is also loaded, but displays an error "content blocked", so maybe the WOPI request fails
> 
> To solve the first thing, I added "else return" to the "if ($currentUser !== null) {" in appinfo/app.php. But the more logical way is maybe to remove this if statement here complete and let the PermissionManager handle NULL user objets correctly, based on a config option.
> 
> The second thing is strange, because the viewer.js / Application class should not be loaded by app.php if the user is not a member of the group. But, I don't know why and where, it's loaded anyway. I duplicated the check from app.php to the begin of the Application.php constructor and created a "enabled" field in the class, set in the constructor (and exited the contructor after this if false). I used this field to exit "registerProvider" after calling immediatly, if false.

Hi,

I would love to see this working, the second thing to be more specific. I tried to guess what you did but could not manage to get rid of the 'content blocked' stuff. I tried to exit pretty everything (and verify that I'm effectively considered not in a group which can use the app) in Application.php but without any results, or worst, by disabling the app no matter what.

**Comment by alx-tuilmenau** [comment]
Hi,
I don't know since which version, but 2.0.3 has here no problems if limited to a group, so you don't need the ugly workaround from my message in 2023 anymore.

**Comment by Orchal** [comment]
Well, not for me. It wasn't working on 2.0.3, neither 2.1.0...

**Comment by alx-tuilmenau** [comment]
I checked it on my installation, and also got the problem again here (same situation, richdocuments and officeonline with different groups). 
The problem is the viewer JS, it's loaded even if the app is disabled for the user. I tried to fix it (and the code below works on my test system), but I don't have internet access on my test system and can't create a pull request. Therefore I would write my suggested changes here.

In lib/Listener/FilesScriptListener.php and LoadViewerListener.php I added some lines to check the user.  

LoadViewerListener.php:
```
<?php

declare(strict_types=1);

namespace OCA\Officeonline\Listener;

use OCA\Officeonline\PermissionManager;
use OCP\EventDispatcher\Event;
use OCP\EventDispatcher\IEventListener;
use OCP\Util;

class LoadViewerListener implements IEventListener {
        /** @var PermissionManager */
        private $permissionManager;

        public function __construct(PermissionManager $permissionManager) {
                $this->permissionManager = $permissionManager;
        }

        public function handle(Event $event): void {
                $currentUser = \OC::$server->getUserSession()->getUser();
                if ($currentUser != null && $this->permissionManager->isEnabledForUser($currentUser)) {
                        Util::addScript('officeonline', 'viewer');
                }
        }
}
```

The "$currentUser != null" disables the app for anonymous users. The isEnabledForUser has no rule if the user is null, maybe it's a better solution to check the null value there to allow the app to load for anonymous users, if the group restriction is not enabled.

FilesScriptListener.php in the same way, only with the different addScript Line from the original file.

**Comment by Orchal** [comment]
Ok, I did some tests, I found a few issues but not directly related to group limitation, although it could (should?) be.

Work as intended => locks. Everything is handled correctly, we can't edit a file which is currently open by local editor neither both of the online editors. We could expect that, it works and it's perfect.

Kind of the same issue exists on both richdocuments and officeonline concerning the limitaion to groups:
 - with officeonline, no matter if the limitation to groups is set or not, guest users can't create new files. There are no issues whatsoever with the limitaion for registered users
 - with richdocuments, no matter if the limitaion to groups is set or not, everyone have the option to create new files

I'm gonna complete issues about limitation to groups on richdocuments.

**Comment by alx-tuilmenau** [comment]
For richdocuments, the ability to use it as public / share link user depends on the permission of the link owner. If the owner is allowed to use richdocuments, it will also enabled for the link share. For me, I disabled (commented out) the registration of ShareLinkListener in AppInfo/Application.php to never load richdocuments for link shares. 
With officeonline I have no idea, the Application.php registers the templates for public users, I don't know why they won't show up.

**Comment by Orchal** [comment]
> For richdocuments, the ability to use it as public / share link user depends on the permission of the link owner. If the owner is allowed to use richdocuments, it will also enabled for the link share. For me, I disabled (commented out) the registration of ShareLinkListener in AppInfo/Application.php to never load richdocuments for link shares. With officeonline I have no idea, the Application.php registers the templates for public users, I don't know why they won't show up.

Good catch for richdocuments, it looks like to be a good idea and office online could work the same way...
